language: cpp

branches:
  only: 
    - master

env:
- PYTHON_BUILD_VERSION=3.7

dist: xenial
sudo: false

addons:
  apt:
    packages:
    - git 
    - cmake 
    - build-essential 
    - libxmu-dev 
    - libxi-dev 
    - xorg-dev
    - freeglut3-dev 
    - libglfw3-dev 
    - libglew-dev

script: |
  git submodule update --init --recursive

  # ----------------
  # test cpp
  cd 3rd_party/googletest
  cmake .
  make
  cd ../../

  cd test_cpp
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=OFF ..
  make
  make test 
  ./runUnitTests
  cd ../../

  cd test_cpp
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=ON ..
  make
  make test 
  ./runUnitTests
  cd ../../

  # --------------------------
  # build c++ glut examples
  cd examples_glut
  mkdir buildMake
  cd buildMake
  cmake ..
  make -i
  cd ../..

  # -------------------------
  # build C++ glfw examples
  cd 3rd_party/glfw
  cmake .
  make
  cd ../..

  cd examples_glfwold
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make -i
  cd ../..

  cd examples_glfwold
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=OFF ..
  make -i
  cd ../..

  cd examples_glfwnew
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make -i
  cd ../..

  cd examples_glfwnew
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=OFF ..
  make -i
  cd ../..