language: cpp

branches:
  only: 
    - master

env:
- PYTHON_BUILD_VERSION=3.7

dist: xenial
sudo: false

addons:
  apt:
    packages:
    - git 
    - cmake 
    - build-essential 
    - libxmu-dev 
    - libxi-dev 
    - xorg-dev
    - freeglut3-dev 
    - libglfw3-dev 
    - libglew-dev

script: |
  git submodule update --init --recursive

  echo "# --------------------------"
  echo "# build c++ glut examples"
  cd examples_glut
  mkdir buildMake
  cd buildMake
  cmake ..
  make
  cd ../..

  echo "# ----------------"
  echo "# test cpp"
  cd 3rd_party/googletest
  cmake .
  make
  cd ../../

  cd test_cpp
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=OFF ..
  make
  make test 
  ./runUnitTests
  cd ../../

  cd test_cpp
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=ON ..
  make
  make test 
  ./runUnitTests
  cd ../../


  echo "# -------------------------"
  echo "# build C++ glfw examples"
  cd 3rd_party/glfw
  cmake .
  make
  cd ../..

  cd examples_glfwold
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../..

  cd examples_glfwold
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=OFF ..
  make
  cd ../..

  cd examples_glfwnew
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../..

  cd examples_glfwnew
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=OFF ..
  make
  cd ../..

  echo "# -------------------------"
  echo "# build tinyglfw examples"
  cd examples_glfw_tinygltf_oldgl
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../../

  echo "# --------------------------"
  echo "# build glfw_thread examples"
  cd examples_glfw_thread_oldgl
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../../  