# This is a basic workflow to help you get started with Actions

name: CI_Linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout repository
      uses: actions/checkout@v2   

    - name: download_dependencies
      run: |
        git submodule update --init --recursive       

    - name: test_cpp
      run: |
        echo "###################"
        echo "## build googletest"
        cd 3rd_party/googletest
        cmake .
        make
        cd ../../

        echo "#############################"
        echo "## build test hdronly and run"
        cd test_cpp
        mkdir buildMakeHdronly && cd buildMakeHdronly
        cmake -DUSE_HEADERONLY=OFF ..
        make
        make test 
        ./runUnitTests
        cd ../../

        echo "############################"
        echo "## build test static" 
        cd test_cpp
        mkdir buildMakeStatic && cd buildMakeStatic
        cmake -DUSE_HEADERONLY=ON ..
        make
        make test 
        ./runUnitTests
        cd ../../    
